[package]
name = "navi"
version = "2.4.1"
authors = ["Denis Isidoro <denis_isidoro@live.com>"]
edition = "2018"
description = "An interactive cheatsheet tool for the command-line"
homepage = "https://github.com/denisidoro/navi"
documentation = "https://github.com/denisidoro/navi"
repository = "https://github.com/denisidoro/navi"
keywords = ["cheatsheets", "terminal", "cli", "tui", "shell"]
categories = ["command-line-utilities"]
license = "Apache-2.0"

[badges]
travis-ci = { repository = "denisidoro/navi", branch = "master" }

[dependencies]
regex = "1.3.4"
structopt = "0.3"
termion = "1.5.5"
raw_tty = "0.1.0"
lazy_static = "1.4.0"
dirs = "2.0.0"
terminal_size = "0.1.10"
walkdir = "2"
shellwords = "1.0.0"
anyhow = "1.0.27"
thiserror = "1.0.12"
skim = "~0.8.0"

[dependencies.git2]
version = "0.10.0"
default-features = false
features = ["https"]

[target.'cfg(target_os = "macos")'.dependencies.git2]
version = "0.10.0"
default-features = false
features = ["vendored-openssl"]

[lib]
name = "navi"
path = "src/lib.rs"

[[bin]]
name = "navi"
path = "src/bin/main.rs"
bench = false
